name: issue labeler workflow

on:
  issues:
    types: ["opened"]

jobs:
  Issue-Labeler:
    name: issue labeler
    runs-on: ubuntu-latest
    steps:
      - uses: Renato66/auto-label@v2.3.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          ignore-comments: true
          default-labels: '["Triage"]'
